########################################################################################################################
#
#  ░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░
#  ░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗
#  ░╚██╗████╗██╔╝███████║██████╔╝██████╔╝
#  ░░████╔═████║░██╔══██║██╔══██╗██╔═══╝░
#  ░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██║░░░░░
#  ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░
#
# Commands:
#
#
########################################################################################################################

enable: true

kick-default-reason: "You have been kicked"

