name: Essentials
version: '${version}'
main: fr.maxlego08.essentials.ZEssentialsPlugin
folia-supported: true
description: Provides an essential, core set of commands for Bukkit.
depend:
  - zMenu
  - PlaceholderAPI
softdepend:
  - Vault
api-version: '1.20'
