name: Bug report
about: Create a report to help us improve
title: ''
labels: ["type: bug"]
assignees: Maxlego08
body:
  - type: markdown
    attributes:
      value: |
        ## READ AND FOLLOW THE DESCRIPTIONS OF THIS ISSUE TEMPLATE!
        Not doing so may result in your issue being closed without warning. Take your time and properly fill out everything as requested.
        We advise you to put a maximum of image and video to better understand your problem.
  - type: checkboxes
    id: searched
    attributes:
      label: Terms
      options:
        - label: "I'm using the very latest version of zEssentials and its dependencies (zMenu and PlaceholdersAPI)."
          required: true
        - label: "I am sure this is a bug and it is not caused by a misconfiguration or by another plugin."
          required: true
        - label: "I've looked for already existing issues on the [Issue Tracker](https://github.com/Maxlego08/zEssentials/issues) and haven't found any."
          required: true
        - label: "I already searched on the [plugin wiki](https://zessentials.groupez.dev/) to know if a solution is already known."
          required: true
        - label: "I already searched on the [discord](https://discord.groupez.dev/) to check if anyone already has a solution for this."
          required: true
        - label: "I tested this with just zEssentials and its dependencies and with a vanilla client of the same version as the Server."
          required: true
        - label: "I enabled the debug mode in config.yml and sql debug"
          required: true    
