########################################################################################################################
#
# ░██╗░░░░░░░██╗░█████╗░██████╗░██╗░░░░░██████╗░███████╗██████╗░██╗████████╗
# ░██║░░██╗░░██║██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝
# ░╚██╗████╗██╔╝██║░░██║██████╔╝██║░░░░░██║░░██║█████╗░░██║░░██║██║░░░██║░░░
# ░░████╔═████║░██║░░██║██╔══██╗██║░░░░░██║░░██║██╔══╝░░██║░░██║██║░░░██║░░░
# ░░╚██╔╝░╚██╔╝░╚█████╔╝██║░░██║███████╗██████╔╝███████╗██████╔╝██║░░░██║░░░
# ░░░╚═╝░░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░╚══════╝╚═════╝░╚═╝░░░╚═╝░░░
#
# Documentation: https://zessentials.groupez.dev/modules/worldedit
#
########################################################################################################################

enable: true

items:
  playerWand:
    max-use: 50
    price-multiplier: 1.2
    max-blocks: 500
    max-distance: 20
    item:
      material: BLAZE_ROD
      name: "#eb5021ᴡᴏʀʟᴅᴇᴅɪᴛ"
      lore:
        - ''
        - '#ffd353ℹ Informations#3f3f3f:'
        - '#3f3f3f• &7Select two positions for'
        - '#3f3f3f• &7place or destroy blocks'
        - ''
        - '#3f3f3f• &7Max Blocks#3f3f3f: #4cd5ff500'
        - '#3f3f3f• &7Max Distance#3f3f3f: #4cd5ff20'
        - '#3f3f3f• &7Use#3f3f3f: #4cd5ff%use%#3f3f3f/#4cf8ff50'
        - ''
  adminWand:
    max-use: -1
    price-multiplier: 0
    max-blocks: -1
    max-distance: -1
    item:
      material: BLAZE_ROD
      name: "#eb5021ᴡᴏʀʟᴅᴇᴅɪᴛ"
      lore:
        - ''
        - '#ffd353ℹ Informations#3f3f3f:'
        - '#3f3f3f• &7Select two positions for'
        - '#3f3f3f• &7place or destroy blocks'
        - ''
        - '#3f3f3f• &7Max Blocks#3f3f3f: #4cd5ff∞'
        - '#3f3f3f• &7Max Distance#3f3f3f: #4cd5ff∞'
        - '#3f3f3f• &7Use#3f3f3f: #4cd5ff%use%#3f3f3f/#4cf8ff∞'
        - ''

blacklist-blocks:
  - SLIME_BLOCK
  - HONEY_BLOCK
  - STRING
  - AMETHYST_CLUSTER
  - MEDIUM_AMETHYST_BUD
  - LARGE_AMETHYST_BUD
  - SMALL_AMETHYST_BUD
  - HOPPER
  - NOTE_BLOCK
  - PISTON_HEAD
  - STICKY_PISTON_HEAD
  - END_PORTAL
  - REDSTONE_WALL_TORCH
  - WALL_TORCH
  - REDSTONE
  - CAULDRON
  - MOB_SPAWNER
  - SPAWNER
  - TNT
  - BEDROCK
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - HOPPER
  - BAMBOO_SAPLING
  - BLACK_CONCRETE_POWDER
  - BLUE_CONCRETE_POWDER
  - YELLOW_CONCRETE_POWDER
  - GREEN_CONCRETE_POWDER
  - LIGHT_GRAY_CONCRETE_POWDER
  - GRAY_CONCRETE_POWDER
  - CYAN_CONCRETE_POWDER
  - WHITE_CONCRETE_POWDER
  - BROWN_CONCRETE_POWDER
  - PURPLE_CONCRETE_POWDER
  - RED_CONCRETE_POWDER
  - MAGENTA_CONCRETE_POWDER
  - ORANGE_CONCRETE_POWDER
  - LIME_CONCRETE_POWDER
  - LIGHT_BLUE_CONCRETE_POWDER
  - PINK_CONCRETE_POWDER
  - BARREL
  - BAMBOO
  - END_PORTAL
  - ENDER_PORTAL
  - ENDER_PORTAL_FRAME[facing=south]
  - ENDER_PORTAL_FRAME[facing=west]
  - ENDER_PORTAL_FRAME[facing=east]
  - ENDER_PORTAL_FRAME
  - END_PORTAL_FRAME[facing=south]
  - END_PORTAL_FRAME[facing=west]
  - END_PORTAL_FRAME[facing=east]
  - END_PORTAL_FRAME
  - FURNACE
  - ITEM_FRAME
  - REDSTONE_TORCH
  - TORCH
  - SOUL_TORCH
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - LIME_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - RED_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GREEN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - PINK_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - PISTON
  - NETHER_PORTAL
  - END_GATEWAY
  - STICKY_PISTON
  - DISPENSER
  - DROPPER
  - ARMOR_STAND
  - OBSERVER
  - ENCHANTING_TABLE
  - REPEATER
  - SAND
  - RED_SAND
  - GRAVEL
  - DAMAGED_ANVIL
  - CHIPPED_ANVIL
  - ANVIL
  - CARROTS
  - WHEAT
  - POTATOES
  - beetroots
  - CACTUS
  - SUGAR_CANE
  - CHORUS_PLANT
  - COCOA
  - WITHER_SKELETON_SKULL
  - WITHER_SKELETON_WALL_SKULL
  - PLAYER_HEAD
  - PLAYER_WALL_HEAD
  - FIRE
  - PUMPKIN
  - MELON
  - CARVED_PUMPKIN
  - CHORUS_FLOWER
  - LAVA
  - SWEET_BERRY_BUSH
  - BROWN_MUSHROOM
  - CAVE_AIR
  - COMMAND_BLOCK
  - CRIMSON_FUNGUS
  - JIGSAW
  - KELP
  - KELP_PLANT
  - NETHER_WART
  - RED_MUSHROOM
  - SCAFFOLDING
  - SEAGRASS
  - TALL_SEAGRASS
  - VOID_AIR
  - WARPED_FUNGUS
  - DRAGON_EGG
  - BEACON
  - WEEPING_VINES
  - TWISTING_VINES
  - DIAMOND_BLOCK
  - EMERALD_BLOCK
  - QUARTZ_BLOCK
  - GOLD_BLOCK
  - COAL_BLOCK
  - IRON_BLOCK
  - REDSTONE_BLOCK
  - COPPER_BLOCK
  - LAPIS_BLOCK
  - AMETHYST_BLOCK