########################################################################################################################
#
# ██████╗░██╗░██████╗░█████╗░░█████╗░██████╗░██████╗░
# ██╔══██╗██║██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║░░██║██║╚█████╗░██║░░╚═╝██║░░██║██████╔╝██║░░██║
# ██║░░██║██║░╚═══██╗██║░░██╗██║░░██║██╔══██╗██║░░██║
# ██████╔╝██║██████╔╝╚█████╔╝╚█████╔╝██║░░██║██████╔╝
# ╚═════╝░╚═╝╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░
#
# This module allows you to display information about your discord through a webhook, more information here:
# https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
#
# You must define the URL of the webhook and the type of logo display
#
# AVATAR: https://mc-heads.net/#basic
# ISOMETRIC: https://mc-heads.net/#isometric
# NONE: Will display the webhook discord logo by default
#
########################################################################################################################

enable: true

# Send the player’s message on your discord
chat-message:
  enable: false
  webhook: "https://discord.com/api/webhooks/"
  avatar-type: AVATAR
  message: "%message%"
  username: "%player%"

# Send a message when a player logs in
join-message:
  enable: false
  webhook: "https://discord.com/api/webhooks/"
  avatar-type: ISOMETRIC
  message: "%player% just logged in"
  type: WEBHOOK
  webhook-color: "#00ff00"

# Send a message when a player logs out
left-message:
  enable: false
  webhook: "https://discord.com/api/webhooks/"
  avatar-type: NONE
  message: "%player% just logged out"
  type: WEBHOOK
  webhook-color: "#ff0000"

# Sends a message when the player first logs in
first-join-message:
  enable: false
  webhook: "https://discord.com/api/webhooks/"
  avatar-type: NONE
  message: "%player% just logged out"
  type: WEBHOOK
  webhook-color: "#ff0000"