########################################################################################################################
#
#  ░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░
#  ░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗
#  ░╚██╗████╗██╔╝███████║██████╔╝██████╔╝
#  ░░████╔═████║░██╔══██║██╔══██╗██╔═══╝░
#  ░░╚██╔╝░╚██╔╝░██║░░██║██║░░██║██║░░░░░
#  ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░
#
# Commands:
#
#
########################################################################################################################

enable: true

enable-inventory: false

enable-no-argument-message: true

