########################################################################################################################
#
# ██╗░░██╗░█████╗░██╗░░░░░░█████╗░░██████╗░██████╗░░█████╗░███╗░░░███╗
# ██║░░██║██╔══██╗██║░░░░░██╔══██╗██╔════╝░██╔══██╗██╔══██╗████╗░████║
# ███████║██║░░██║██║░░░░░██║░░██║██║░░██╗░██████╔╝███████║██╔████╔██║
# ██╔══██║██║░░██║██║░░░░░██║░░██║██║░░╚██╗██╔══██╗██╔══██║██║╚██╔╝██║
# ██║░░██║╚█████╔╝███████╗╚█████╔╝╚██████╔╝██║░░██║██║░░██║██║░╚═╝░██║
# ╚═╝░░╚═╝░╚════╝░╚══════╝░╚════╝░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═╝
#
# Documentation: https://zessentials.groupez.dev/modules/hologram
#
########################################################################################################################

enable: true
