########################################################################################################################
#
# ██╗░░░██╗░█████╗░██╗░░░██╗██╗░░░░░████████╗
# ██║░░░██║██╔══██╗██║░░░██║██║░░░░░╚══██╔══╝
# ╚██╗░██╔╝███████║██║░░░██║██║░░░░░░░░██║░░░
# ░╚████╔╝░██╔══██║██║░░░██║██║░░░░░░░░██║░░░
# ░░╚██╔╝░░██║░░██║╚██████╔╝███████╗░░░██║░░░
# ░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚══════╝░░░╚═╝░░░
#
# Documentation: https://zessentials.groupez.dev/modules/vault
#
########################################################################################################################

enable: true

max-vaults: 7

icon-open: "MINECART"

icon-close: "CHEST_MINECART"

vault-name-regex: "^[a-zA-Z0-9_-]{3,16}$"

vault-permissions:
  - permission: zessentials.vault.size.player
    slots: 45
  - permission: zessentials.vault.size.vip
    slots: 90
  - permission: zessentials.vault.size.admin
    slots: 500