########################################################################################################################
#
# ██╗░░░██╗░█████╗░██╗░░░██╗██╗░░░░░████████╗
# ██║░░░██║██╔══██╗██║░░░██║██║░░░░░╚══██╔══╝
# ╚██╗░██╔╝███████║██║░░░██║██║░░░░░░░░██║░░░
# ░╚████╔╝░██╔══██║██║░░░██║██║░░░░░░░░██║░░░
# ░░╚██╔╝░░██║░░██║╚██████╔╝███████╗░░░██║░░░
# ░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚══════╝░░░╚═╝░░░
#
# Documentation: https://zessentials.groupez.dev/modules/vault
#
########################################################################################################################

enable: true

max-vaults: 7

icon-open: "MINECART"

icon-close: "CHEST_MINECART"