########################################################################################################################
#
# ░██████╗░█████╗░░█████╗░██████╗░███████╗██████╗░░█████╗░░█████╗░██████╗░██████╗░
# ██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ╚█████╗░██║░░╚═╝██║░░██║██████╔╝█████╗░░██████╦╝██║░░██║███████║██████╔╝██║░░██║
# ░╚═══██╗██║░░██╗██║░░██║██╔══██╗██╔══╝░░██╔══██╗██║░░██║██╔══██║██╔══██╗██║░░██║
# ██████╔╝╚█████╔╝╚█████╔╝██║░░██║███████╗██████╦╝╚█████╔╝██║░░██║██║░░██║██████╔╝
# ╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░
#
# Documentation: https://zessentials.groupez.dev/modules/scoreboard
# FastBoard: https://github.com/MrMicky-FR/FastBoard
#
########################################################################################################################

enable: true

scoreboards:
  default:
    default: true
    title: "#b3722dzEssentials"
    lines:
      - line: 1
        text: "&7Joueurs: &a%online%"
      - line: 2
        text: "&7Argent: &a$%vault_eco_balance_formatted%"
      - line: 3
        text: "&7Kills: &a%statistic_player_kills%"
      - line: 4
        text: "&7Décès: &a%statistic_deaths%"
      - line: 5
        text: "&7Animation: &a{animation}"
